name: Main
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Docker Publish
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Gateway
          file: ./Gateway/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/audiomind-gateway:latest

  deploy:
    needs: publish
    name: Docker Publish
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Gateway
          file: ./Gateway/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/audiomind-gateway:latest
