name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER  }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD  }}\
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Gateway/Dockerfile
          push: true
          tags: ${{ secrets.CI_REGISTRY_USER }}/audiomind-gateway:latest