name: Snyk
on:
  push:
    branches:
      - '!main'   # excludes main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    name: Analyze security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@master
      - name: Restore dependencies
        run: dotnet restore ./Gateway.sln
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor --file=./Gateway.sln
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
